### ISSUE TITLE
General

### ISSUE THREAD

**Issue by IanaKhitsko** [13LD/TTPS#1]
Requirements shall be written for the blog, not to the euro diffusion utility. Check corresponding ppt.

**Comment by 13LD** [comment]
@IanaKhitsko , I have written issues on the euro diffusion [`project`](https://github.com/romick101/euro-diffusion/issues?q=is%3Aissue+is%3Aclosed+author%3A13LD), and added requirements as it was mentioned on the ppt
<img width="724" alt="screen shot 2018-12-24 at 15 53 40" src="https://user-images.githubusercontent.com/9123189/50401023-41ae3180-0794-11e9-8140-c80d606dbbae.png">
